# Generated by Django 5.2.8 on 2025-11-15 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Categoría')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código Único')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Activo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_adquisicion', models.DateField(verbose_name='Fecha de Adquisición')),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Inicial')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='activos.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
            },
        ),
    ]
