# Generated by Django 5.2.8 on 2025-11-15 19:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activo',
            options={'ordering': ['-fecha_adquisicion'], 'verbose_name': 'Activo', 'verbose_name_plural': 'Activos'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AddField(
            model_name='activo',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AddField(
            model_name='activo',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activo',
            name='estado',
            field=models.CharField(choices=[('AC', 'Activo'), ('MA', 'En Mantenimiento'), ('DB', 'Dado de Baja'), ('RE', 'En Reparación')], db_index=True, default='AC', help_text='Estado actual del activo', max_length=2, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='activo',
            name='numero_serie',
            field=models.CharField(blank=True, help_text='Número de serie o identificador único del fabricante', max_length=100, null=True, unique=True, verbose_name='Número de Serie'),
        ),
        migrations.AddField(
            model_name='activo',
            name='responsable',
            field=models.CharField(blank=True, help_text='Persona o departamento responsable del activo', max_length=200, null=True, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='activo',
            name='ubicacion',
            field=models.CharField(blank=True, help_text='Ubicación física del activo', max_length=200, null=True, verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='activa',
            field=models.BooleanField(db_index=True, default=True, help_text='Desmarcar para desactivar la categoría sin eliminarla', verbose_name='Activa'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción opcional de la categoría', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='categoria',
            field=models.ForeignKey(help_text='Categoría a la que pertenece el activo', on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='activos.categoria', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción detallada del activo', null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='fecha_adquisicion',
            field=models.DateField(db_index=True, help_text='Fecha en que se adquirió el activo', verbose_name='Fecha de Adquisición'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='nombre',
            field=models.CharField(db_index=True, help_text='Nombre descriptivo del activo', max_length=200, verbose_name='Nombre del Activo'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='valor_inicial',
            field=models.DecimalField(db_index=True, decimal_places=2, help_text='Valor de adquisición del activo', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Inicial'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='codigo',
            field=models.CharField(db_index=True, help_text='Código corto para identificación rápida (ej: ELEC)', max_length=10, unique=True, verbose_name='Código Único'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(help_text='Nombre descriptivo de la categoría (ej: Electrónica)', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Nombre de la Categoría'),
        ),
        migrations.AddIndex(
            model_name='activo',
            index=models.Index(fields=['categoria', 'estado'], name='activos_act_categor_21d9be_idx'),
        ),
        migrations.AddIndex(
            model_name='activo',
            index=models.Index(fields=['estado', 'fecha_adquisicion'], name='activos_act_estado_f78c25_idx'),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['codigo', 'activa'], name='activos_cat_codigo_3f5a58_idx'),
        ),
        migrations.AddConstraint(
            model_name='activo',
            constraint=models.CheckConstraint(condition=models.Q(('valor_inicial__gt', 0)), name='activo_valor_positivo', violation_error_message='El valor inicial debe ser positivo'),
        ),
    ]
